version: '3.2'
services:
  terrabrasilis-webapp-test:
    image: terrabrasilis/terrabrasilis-webapp:v2.0.5-test
    hostname: terrabrasilis.webapp
    networks:
      - proxy
    ports:
      - 2222:80
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

networks:
  proxy:
    external: true